const STORAGE_KEY = 'vibetodo-workspace-v1';
const uid = () => Math.random().toString(36).slice(2, 9);
const demoData = { selectedProjectId:'p1', projects:[{id:'p1',name:'vibetodo',description:'여러 프로젝트의 바이브 코딩 흐름을 한 곳에서 관리합니다.',color:'#b9f56b',notes:['한 번에 하나의 TODO만 진행하기','기능 구현 후 바로 검증하기'],files:[{id:'f1',name:'MVP 출시',fileName:null,todos:[{id:'t1',title:'프로젝트 대시보드 레이아웃 구성',status:'done',priority:'high',estimate:'1h'},{id:'t2',title:'프로젝트별 TODO 파일 모델 만들기',status:'done',priority:'high',estimate:'1.5h'},{id:'t3',title:'진행률과 다음 TODO 카드 연결',status:'doing',priority:'high',estimate:'1h'},{id:'t4',title:'JSON 백업 / 복원 기능 추가',status:'todo',priority:'medium',estimate:'1h'}]},{id:'f2',name:'다음 개선',fileName:null,todos:[{id:'t5',title:'키보드 단축키 지원',status:'todo',priority:'low',estimate:'30m'},{id:'t6',title:'마감일과 알림 추가',status:'todo',priority:'medium',estimate:'2h'}]}]}]};
let data = load(); let activeFileId = null; let filter = 'all';
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(demoData);}catch{return structuredClone(demoData);}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));document.querySelector('#save-status').textContent='자동 저장됨 · 방금';}
function project(){return data.projects.find(p=>p.id===data.selectedProjectId)||data.projects[0];}
function allTodos(p){return p.files.flatMap(f=>f.todos||[]);}
function activeFile(p){return p.files.find(f=>f.id===activeFileId)||p.files[0];}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function parseMarkdown(content){
  const lines=content.split(/\r?\n/); const todos=[];
  lines.forEach((line,lineIndex)=>{const match=line.match(/^(\s*[-*+]\s+)\[([ xX>])\]\s+(.*)$/);if(!match)return;let title=match[3].trim();let priority='medium';if(/^\[(high|medium|low)\]\s*/i.test(title)){priority=title.match(/^\[(high|medium|low)\]/i)[1].toLowerCase();title=title.replace(/^\[(high|medium|low)\]\s*/i,'');}const estimate=title.match(/\s+\(([^)]+)\)$/)?.[1]||'';if(estimate)title=title.replace(/\s+\([^)]+\)$/,'');todos.push({id:uid(),title,status:match[2].toLowerCase()==='x'?'done':match[2]==='>'?'hold':'todo',priority,estimate,lineIndex,prefix:match[1],originalLine:line});});
  return todos;
}
function markdownLine(todo){return `${todo.prefix||'- '}[${todo.status==='done'?'x':todo.status==='hold'?'>':' '}] [${todo.priority}] ${todo.title}${todo.estimate?` (${todo.estimate})`:''}`;}
function syncFileContent(file){const lines=(file.content||'').split(/\r?\n/);file.todos.forEach(todo=>{if(Number.isInteger(todo.lineIndex))lines[todo.lineIndex]=markdownLine(todo);});file.content=lines.join('\n');}
async function persistFile(file){const p=project();if(!p.folderPath||!file.fileName||!window.electronAPI)return true;syncFileContent(file);const result=await window.electronAPI.writeMarkdown({folderPath:p.folderPath,fileName:file.fileName,content:file.content});if(!result.ok){toast(`파일 저장 실패: ${result.error}`);return false;}return true;}
async function refreshFolder(p,notify=true){if(!p.folderPath||!window.electronAPI)return;const result=await window.electronAPI.readMarkdownFolder(p.folderPath);if(!result.ok){toast(`TODO 폴더를 읽을 수 없습니다: ${result.error}`);return;}p.files=result.files.map(raw=>({id:uid(),name:raw.name,fileName:raw.fileName,isMain:raw.isMain,content:raw.content,todos:parseMarkdown(raw.content)}));activeFileId=p.files[0]?.id||null;save();render();if(notify)toast(`${p.files.length}개의 Markdown 파일을 읽었습니다.`);}
function render(){const p=project();if(!p)return;const file=activeFile(p);if(file)activeFileId=file.id;const todos=allTodos(p),done=todos.filter(t=>t.status==='done').length,doing=todos.filter(t=>t.status==='doing').length,progress=todos.length?Math.round(done/todos.length*100):0;document.querySelector('#breadcrumb-project').textContent=p.name;document.querySelector('#project-title').textContent=p.name;document.querySelector('#project-description').textContent=p.folderPath?`TODO 폴더 · ${p.folderPath}`:(p.description||'설명이 없습니다.');document.querySelector('#choose-folder').textContent=p.folderPath?'TODO 폴더 다시 연결':'TODO 폴더 연결';renderNav();document.querySelector('#stats-grid').innerHTML=`<div class="stat-card"><div class="stat-label">전체 TODO</div><div class="stat-value">${todos.length}<small>items</small></div></div><div class="stat-card"><div class="stat-label">완료</div><div class="stat-value">${done}<small>/ ${todos.length}</small></div></div><div class="stat-card"><div class="stat-label">진행 중</div><div class="stat-value">${doing}<small>active</small></div></div><div class="stat-card"><div class="stat-label">TODO 파일</div><div class="stat-value">${p.files.length}<small>files</small></div></div>`;renderFocus(todos);renderFiles(p,file);renderTodos(file);renderHealth(todos,progress);renderNotes(p);}
function renderNav(){document.querySelector('#project-nav').innerHTML=data.projects.map(p=>`<button class="project-item ${p.id===data.selectedProjectId?'active':''}" data-project="${p.id}"><i class="project-dot" style="background:${p.color||'var(--accent-2)'}"></i>${escapeHtml(p.name)}<span class="project-count">${allTodos(p).filter(t=>t.status!=='done').length}</span></button>`).join('');document.querySelectorAll('[data-project]').forEach(b=>b.onclick=async()=>{data.selectedProjectId=b.dataset.project;activeFileId=null;const p=project();if(p.folderPath)await refreshFolder(p,false);save();render();});}
function renderFocus(todos){const next=todos.find(t=>t.status==='doing')||todos.find(t=>t.status==='todo');document.querySelector('#next-todo-card').innerHTML=next?`<div class="focus-content"><div class="focus-icon">→</div><div><p class="eyebrow">NEXT UP · ${next.priority.toUpperCase()} PRIORITY</p><h3>${escapeHtml(next.title)}</h3><p>이 항목을 완료하면 다음 작업으로 넘어갈 수 있습니다. 예상 ${escapeHtml(next.estimate||'미정')}</p></div><span class="focus-tag">${next.status==='doing'?'진행 중':'다음 작업'}</span></div>`:`<div class="focus-content"><div class="focus-icon">✓</div><div><p class="eyebrow">ALL CLEAR</p><h3>현재 프로젝트의 TODO를 모두 완료했습니다.</h3><p>새로운 TODO를 추가하거나 다음 프로젝트로 이동해보세요.</p></div></div>`;}
function fileProgress(file){const total=file?.todos.length||0;const done=file?.todos.filter(t=>t.status==='done').length||0;return {total,done,percent:total?Math.round(done/total*100):0};}
function renderFiles(p,file){document.querySelector('#file-tabs').innerHTML=p.files.length?p.files.map(f=>{const stats=fileProgress(f);return `<button class="file-tab ${f.id===file?.id?'active':''}" data-file="${f.id}"><span class="file-tab-name">${f.isMain?'★ ':''}${escapeHtml(f.name)}</span><span class="file-tab-stats"><span>${stats.done}/${stats.total}</span><span class="file-progress"><i style="width:${stats.percent}%"></i></span><span>${stats.percent}%</span></span></button>`;}).join(''):'<div class="empty">연결된 폴더에 Markdown 파일이 없습니다.</div>';document.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>{activeFileId=b.dataset.file;render();});const stats=fileProgress(file);document.querySelector('#file-meta').textContent=`${file?.isMain?'메인 TODO · ':''}${file?.name||'TODO 파일'} · ${stats.done}/${stats.total}개 완료 · ${stats.percent}%`;}
function renderTodos(file){const list=(file?.todos||[]).filter(t=>filter==='all'||t.status===filter);document.querySelector('#todo-list').innerHTML=list.length?list.map(t=>`<div class="todo-row ${t.status==='done'?'completed':''} ${t.status==='hold'?'on-hold':''}"><button class="check ${t.status==='done'?'done':''} ${t.status==='hold'?'hold':''}" data-toggle="${t.id}">${t.status==='done'?'✓':t.status==='hold'?'›':''}</button><div><div class="todo-title">${escapeHtml(t.title)}</div><div class="todo-meta"><span class="priority ${t.priority}">${t.priority==='high'?'높음':t.priority==='medium'?'보통':'낮음'}</span><span>·</span><span>${escapeHtml(t.estimate||'예상 시간 미정')}</span><span>·</span><span>${t.status==='doing'?'진행 중':t.status==='hold'?'보류':t.status==='done'?'완료':'예정'}</span></div></div><div class="todo-actions"><button class="row-action" data-edit="${t.id}">편집</button><button class="row-action" data-delete="${t.id}">삭제</button></div></div>`).join(''):'<div class="empty">이 필터에 해당하는 TODO가 없습니다.</div>';document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggleTodo(b.dataset.toggle));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openTodoModal(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteTodo(b.dataset.delete));}
function renderHealth(todos,progress){document.querySelector('#health-content').innerHTML=`<div class="health-ring" style="--progress:${progress}%"><div><strong>${progress}%</strong><span>완료율</span></div></div><div class="health-lines"><div class="health-line"><span>완료</span><b>${todos.filter(t=>t.status==='done').length}</b></div><div class="health-line"><span>진행 중</span><b>${todos.filter(t=>t.status==='doing').length}</b></div><div class="health-line"><span>남은 항목</span><b>${todos.filter(t=>t.status!=='done').length}</b></div></div>`;}
function renderNotes(p){document.querySelector('#notes-list').innerHTML=p.notes?.length?p.notes.map((n,i)=>`<div class="note">${escapeHtml(n)}<button data-note="${i}">×</button></div>`).join(''):'<div class="empty">아직 메모가 없습니다.</div>';document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>{p.notes.splice(+b.dataset.note,1);save();render();});}
async function toggleTodo(id){const p=project(),f=p.files.find(file=>file.todos.some(t=>t.id===id)),t=f?.todos.find(item=>item.id===id);if(!t)return;t.status=t.status==='done'?'todo':'done';if(await persistFile(f)){save();render();toast(t.status==='done'?'TODO 완료 및 파일 저장':'TODO를 예정으로 변경');}}
async function deleteTodo(id){const p=project(),f=p.files.find(file=>file.todos.some(t=>t.id===id));if(!f)return;const index=f.todos.findIndex(t=>t.id===id),removed=f.todos[index];f.todos.splice(index,1);if(Number.isInteger(removed?.lineIndex))f.todos.slice(index).forEach(t=>{if(t.lineIndex>removed.lineIndex)t.lineIndex--;});if(p.folderPath&&f.fileName&&Number.isInteger(removed?.lineIndex)){const lines=(f.content||'').split(/\r?\n/);lines.splice(removed.lineIndex,1);f.content=lines.join('\n');const result=await window.electronAPI.writeMarkdown({folderPath:p.folderPath,fileName:f.fileName,content:f.content});if(!result.ok){toast(`파일 저장 실패: ${result.error}`);return;}}save();render();toast('TODO를 삭제했습니다.');}
function modal(title,body,submit){document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>${title}</h2>${body}<div class="modal-actions"><button class="cancel" id="modal-cancel">취소</button><button class="confirm" id="modal-submit">저장</button></div></div></div>`;document.querySelector('#modal-cancel').onclick=closeModal;document.querySelector('#modal-submit').onclick=submit;document.querySelector('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal();};}
function closeModal(){document.querySelector('#modal-root').innerHTML='';}
function openTodoModal(id=null){const f=activeFile(project());const old=f?.todos.find(t=>t.id===id);modal(id?'TODO 편집':'새 TODO',`<div class="form-field"><label>할 일</label><input id="m-title" value="${escapeHtml(old?.title||'')}" placeholder="예: API 에러 처리 추가" autofocus /></div><div class="form-field"><label>상태</label><select id="m-status"><option value="todo" ${!old||old.status==='todo'?'selected':''}>예정</option><option value="doing" ${old?.status==='doing'?'selected':''}>진행 중</option><option value="hold" ${old?.status==='hold'?'selected':''}>보류</option><option value="done" ${old?.status==='done'?'selected':''}>완료</option></select></div><div class="form-field"><label>우선순위</label><select id="m-priority"><option value="high" ${old?.priority==='high'?'selected':''}>높음</option><option value="medium" ${!old||old.priority==='medium'?'selected':''}>보통</option><option value="low" ${old?.priority==='low'?'selected':''}>낮음</option></select></div><div class="form-field"><label>예상 시간</label><input id="m-estimate" value="${escapeHtml(old?.estimate||'')}" placeholder="예: 1h, 30m" /></div>`,async()=>{const title=document.querySelector('#m-title').value.trim();if(!title)return toast('TODO 내용을 입력해주세요.');const item=old||{id:uid(),status:'todo',lineIndex:null,prefix:'- '};item.title=title;item.status=document.querySelector('#m-status').value;item.priority=document.querySelector('#m-priority').value;item.estimate=document.querySelector('#m-estimate').value.trim();if(!old){if(project().folderPath&&f.fileName){f.content=(f.content||'').replace(/\s*$/,'')+`\n${markdownLine(item)}\n`;item.lineIndex=f.content.split(/\r?\n/).length-2;const result=await window.electronAPI.writeMarkdown({folderPath:project().folderPath,fileName:f.fileName,content:f.content});if(!result.ok)return toast(`파일 저장 실패: ${result.error}`);}f.todos.push(item);}else if(!(await persistFile(f)))return;save();closeModal();render();toast(id?'TODO를 수정했습니다.':'TODO를 추가했습니다.');});}
function openFileModal(){const p=project();if(!p.folderPath)return toast('먼저 TODO 폴더를 연결해주세요.');modal('새 TODO 파일',`<div class="form-field"><label>파일 이름</label><input id="m-name" placeholder="예: 2차 개선, 버그 수정" autofocus /></div>`,async()=>{let name=document.querySelector('#m-name').value.trim();if(!name)return toast('파일 이름을 입력해주세요.');if(!name.toLowerCase().endsWith('.md'))name+='.md';const result=await window.electronAPI.createMarkdown({folderPath:p.folderPath,fileName:name,content:'# TODO\n\n'});if(!result.ok)return toast(`파일 생성 실패: ${result.error}`);closeModal();await refreshFolder(p);toast('Markdown TODO 파일을 만들었습니다.');});}
function openProjectModal(){const p=project();modal('프로젝트 편집',`<div class="form-field"><label>프로젝트 이름</label><input id="m-name" value="${escapeHtml(p.name)}" autofocus /></div><div class="form-field"><label>설명</label><textarea id="m-description">${escapeHtml(p.description||'')}</textarea></div>`,()=>{const name=document.querySelector('#m-name').value.trim();if(!name)return toast('프로젝트 이름을 입력해주세요.');p.name=name;p.description=document.querySelector('#m-description').value.trim();save();closeModal();render();});}
function newProject(){modal('새 프로젝트',`<div class="form-field"><label>프로젝트 이름</label><input id="m-name" placeholder="예: habit-tracker" autofocus /></div><div class="form-field"><label>설명</label><textarea id="m-description" placeholder="이 프로젝트에서 만들고 있는 것"></textarea></div>`,()=>{const name=document.querySelector('#m-name').value.trim();if(!name)return toast('프로젝트 이름을 입력해주세요.');const p={id:uid(),name,description:document.querySelector('#m-description').value.trim(),color:'#70d5c2',notes:[],files:[]};data.projects.push(p);data.selectedProjectId=p.id;activeFileId=null;save();closeModal();render();toast('새 프로젝트를 추가했습니다. 이제 TODO 폴더를 연결해주세요.');});}
async function chooseFolder(){if(!window.electronAPI)return toast('폴더 연결은 Electron 앱에서 사용할 수 있습니다.');const folder=await window.electronAPI.chooseFolder();if(!folder)return;project().folderPath=folder;await refreshFolder(project());}
async function syncFiles(){if(!window.electronAPI)return toast('동기화는 Electron 앱에서 사용할 수 있습니다.');if(!project().folderPath)return toast('먼저 TODO 폴더를 연결해주세요.');const button=document.querySelector('#sync-files');button.disabled=true;button.textContent='동기화 중…';await refreshFolder(project(),false);button.disabled=false;button.textContent='↻ 동기화';toast('TODO Markdown 파일을 동기화했습니다.');}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200);}
document.querySelector('#new-project').onclick=newProject;document.querySelector('#new-file').onclick=openFileModal;document.querySelector('#edit-project').onclick=openProjectModal;document.querySelector('#choose-folder').onclick=chooseFolder;document.querySelector('#status-filter').onchange=e=>{filter=e.target.value;render();};document.querySelector('#add-note').onclick=()=>{modal('새 메모',`<div class="form-field"><label>메모</label><textarea id="m-note" placeholder="기억해둘 내용이나 다음에 확인할 점"></textarea></div>`,()=>{const note=document.querySelector('#m-note').value.trim();if(!note)return toast('메모 내용을 입력해주세요.');project().notes.push(note);save();closeModal();render();});};document.querySelector('#export-data').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vibetodo-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('백업 파일을 내보냈습니다.');};document.querySelector('#import-data').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{data=JSON.parse(reader.result);activeFileId=null;save();render();toast('백업을 복원했습니다.');}catch{toast('올바른 JSON 백업 파일이 아닙니다.');}};reader.readAsText(file);};document.querySelector('#reset-demo').onclick=()=>{if(confirm('현재 데이터를 데모 데이터로 초기화할까요?')){data=structuredClone(demoData);activeFileId=null;save();render();toast('데모 데이터로 초기화했습니다.');}};
document.querySelector('#sync-files').onclick=syncFiles;document.querySelector('#new-todo').onclick=()=>{if(!activeFile(project()))return toast('먼저 TODO 파일을 선택해주세요.');openTodoModal();};
if(window.electronAPI)window.electronAPI.getAppInfo().then(info=>{const badge=document.querySelector('#runtime-badge');if(badge)badge.textContent=`ELECTRON ${info.version}`;});
render();
